// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dictionary.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddNewWordRequest struct {
	Word                 *Word    `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNewWordRequest) Reset()         { *m = AddNewWordRequest{} }
func (m *AddNewWordRequest) String() string { return proto.CompactTextString(m) }
func (*AddNewWordRequest) ProtoMessage()    {}
func (*AddNewWordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c04a5ffd1d26433d, []int{0}
}

func (m *AddNewWordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNewWordRequest.Unmarshal(m, b)
}
func (m *AddNewWordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNewWordRequest.Marshal(b, m, deterministic)
}
func (m *AddNewWordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNewWordRequest.Merge(m, src)
}
func (m *AddNewWordRequest) XXX_Size() int {
	return xxx_messageInfo_AddNewWordRequest.Size(m)
}
func (m *AddNewWordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNewWordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddNewWordRequest proto.InternalMessageInfo

func (m *AddNewWordRequest) GetWord() *Word {
	if m != nil {
		return m.Word
	}
	return nil
}

type AddNewWordResponce struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNewWordResponce) Reset()         { *m = AddNewWordResponce{} }
func (m *AddNewWordResponce) String() string { return proto.CompactTextString(m) }
func (*AddNewWordResponce) ProtoMessage()    {}
func (*AddNewWordResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_c04a5ffd1d26433d, []int{1}
}

func (m *AddNewWordResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNewWordResponce.Unmarshal(m, b)
}
func (m *AddNewWordResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNewWordResponce.Marshal(b, m, deterministic)
}
func (m *AddNewWordResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNewWordResponce.Merge(m, src)
}
func (m *AddNewWordResponce) XXX_Size() int {
	return xxx_messageInfo_AddNewWordResponce.Size(m)
}
func (m *AddNewWordResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNewWordResponce.DiscardUnknown(m)
}

var xxx_messageInfo_AddNewWordResponce proto.InternalMessageInfo

func (m *AddNewWordResponce) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByIDRequest) Reset()         { *m = GetByIDRequest{} }
func (m *GetByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetByIDRequest) ProtoMessage()    {}
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c04a5ffd1d26433d, []int{2}
}

func (m *GetByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIDRequest.Unmarshal(m, b)
}
func (m *GetByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIDRequest.Merge(m, src)
}
func (m *GetByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetByIDRequest.Size(m)
}
func (m *GetByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIDRequest proto.InternalMessageInfo

func (m *GetByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetByIDResponce struct {
	Word                 *Word    `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByIDResponce) Reset()         { *m = GetByIDResponce{} }
func (m *GetByIDResponce) String() string { return proto.CompactTextString(m) }
func (*GetByIDResponce) ProtoMessage()    {}
func (*GetByIDResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_c04a5ffd1d26433d, []int{3}
}

func (m *GetByIDResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIDResponce.Unmarshal(m, b)
}
func (m *GetByIDResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIDResponce.Marshal(b, m, deterministic)
}
func (m *GetByIDResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIDResponce.Merge(m, src)
}
func (m *GetByIDResponce) XXX_Size() int {
	return xxx_messageInfo_GetByIDResponce.Size(m)
}
func (m *GetByIDResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIDResponce.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIDResponce proto.InternalMessageInfo

func (m *GetByIDResponce) GetWord() *Word {
	if m != nil {
		return m.Word
	}
	return nil
}

type WordsRequest struct {
	None                 bool     `protobuf:"varint,1,opt,name=none,proto3" json:"none,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WordsRequest) Reset()         { *m = WordsRequest{} }
func (m *WordsRequest) String() string { return proto.CompactTextString(m) }
func (*WordsRequest) ProtoMessage()    {}
func (*WordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c04a5ffd1d26433d, []int{4}
}

func (m *WordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WordsRequest.Unmarshal(m, b)
}
func (m *WordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WordsRequest.Marshal(b, m, deterministic)
}
func (m *WordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WordsRequest.Merge(m, src)
}
func (m *WordsRequest) XXX_Size() int {
	return xxx_messageInfo_WordsRequest.Size(m)
}
func (m *WordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WordsRequest proto.InternalMessageInfo

func (m *WordsRequest) GetNone() bool {
	if m != nil {
		return m.None
	}
	return false
}

type WordsResponce struct {
	Words                []*Word  `protobuf:"bytes,2,rep,name=words,proto3" json:"words,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WordsResponce) Reset()         { *m = WordsResponce{} }
func (m *WordsResponce) String() string { return proto.CompactTextString(m) }
func (*WordsResponce) ProtoMessage()    {}
func (*WordsResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_c04a5ffd1d26433d, []int{5}
}

func (m *WordsResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WordsResponce.Unmarshal(m, b)
}
func (m *WordsResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WordsResponce.Marshal(b, m, deterministic)
}
func (m *WordsResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WordsResponce.Merge(m, src)
}
func (m *WordsResponce) XXX_Size() int {
	return xxx_messageInfo_WordsResponce.Size(m)
}
func (m *WordsResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_WordsResponce.DiscardUnknown(m)
}

var xxx_messageInfo_WordsResponce proto.InternalMessageInfo

func (m *WordsResponce) GetWords() []*Word {
	if m != nil {
		return m.Words
	}
	return nil
}

type Word struct {
	Word                 string   `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Examples             []string `protobuf:"bytes,2,rep,name=examples,proto3" json:"examples,omitempty"`
	Transcription        string   `protobuf:"bytes,3,opt,name=Transcription,proto3" json:"Transcription,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Word) Reset()         { *m = Word{} }
func (m *Word) String() string { return proto.CompactTextString(m) }
func (*Word) ProtoMessage()    {}
func (*Word) Descriptor() ([]byte, []int) {
	return fileDescriptor_c04a5ffd1d26433d, []int{6}
}

func (m *Word) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Word.Unmarshal(m, b)
}
func (m *Word) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Word.Marshal(b, m, deterministic)
}
func (m *Word) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Word.Merge(m, src)
}
func (m *Word) XXX_Size() int {
	return xxx_messageInfo_Word.Size(m)
}
func (m *Word) XXX_DiscardUnknown() {
	xxx_messageInfo_Word.DiscardUnknown(m)
}

var xxx_messageInfo_Word proto.InternalMessageInfo

func (m *Word) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func (m *Word) GetExamples() []string {
	if m != nil {
		return m.Examples
	}
	return nil
}

func (m *Word) GetTranscription() string {
	if m != nil {
		return m.Transcription
	}
	return ""
}

func init() {
	proto.RegisterType((*AddNewWordRequest)(nil), "pb.AddNewWordRequest")
	proto.RegisterType((*AddNewWordResponce)(nil), "pb.AddNewWordResponce")
	proto.RegisterType((*GetByIDRequest)(nil), "pb.GetByIDRequest")
	proto.RegisterType((*GetByIDResponce)(nil), "pb.GetByIDResponce")
	proto.RegisterType((*WordsRequest)(nil), "pb.WordsRequest")
	proto.RegisterType((*WordsResponce)(nil), "pb.WordsResponce")
	proto.RegisterType((*Word)(nil), "pb.Word")
}

func init() { proto.RegisterFile("dictionary.proto", fileDescriptor_c04a5ffd1d26433d) }

var fileDescriptor_c04a5ffd1d26433d = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x6d, 0x9a, 0x6a, 0x32, 0xda, 0xda, 0x8e, 0x28, 0x21, 0x88, 0x84, 0xa5, 0x07, 0x4f,
	0x29, 0x56, 0xaf, 0x1e, 0x94, 0x82, 0x78, 0xf1, 0x10, 0x04, 0x2f, 0x5e, 0x92, 0xec, 0x1e, 0x02,
	0x9a, 0x5d, 0x37, 0x91, 0xda, 0x9f, 0xe5, 0x3f, 0x94, 0xdd, 0xcd, 0xae, 0x4d, 0x05, 0x6f, 0x99,
	0x97, 0xf7, 0xde, 0x64, 0x3e, 0x02, 0x53, 0x5a, 0x95, 0x6d, 0xc5, 0xeb, 0x5c, 0x6e, 0x52, 0x21,
	0x79, 0xcb, 0xd1, 0x13, 0x05, 0xb9, 0x82, 0xd9, 0x1d, 0xa5, 0x4f, 0x6c, 0xfd, 0xc2, 0x25, 0xcd,
	0xd8, 0xc7, 0x27, 0x6b, 0x5a, 0x3c, 0x07, 0x7f, 0xcd, 0x25, 0x8d, 0x06, 0xc9, 0xe0, 0xf2, 0x70,
	0x19, 0xa4, 0xa2, 0x48, 0xf5, 0x6b, 0xad, 0x92, 0x39, 0xe0, 0x76, 0xa4, 0x11, 0xbc, 0x2e, 0x19,
	0x4e, 0xc0, 0xab, 0x4c, 0x22, 0xcc, 0xbc, 0x8a, 0x92, 0x04, 0x26, 0x0f, 0xac, 0xbd, 0xdf, 0x3c,
	0xae, 0x6c, 0xeb, 0xae, 0x63, 0x01, 0xc7, 0xce, 0xd1, 0x95, 0xfc, 0xbf, 0x98, 0xc0, 0x91, 0x9a,
	0x1a, 0x5b, 0x88, 0xe0, 0xd7, 0xbc, 0x66, 0xda, 0x1d, 0x64, 0xfa, 0x99, 0x2c, 0x60, 0xdc, 0x79,
	0xba, 0xca, 0x0b, 0x18, 0xa9, 0x70, 0x13, 0x79, 0xc9, 0xb0, 0xd7, 0x69, 0x64, 0xf2, 0x0a, 0xbe,
	0x1a, 0x55, 0x99, 0x5b, 0x1d, 0x9a, 0x85, 0x18, 0x43, 0xc0, 0xbe, 0xf2, 0x77, 0xf1, 0xc6, 0x4c,
	0x3c, 0xcc, 0xdc, 0x8c, 0x73, 0x18, 0x3f, 0xcb, 0xbc, 0x6e, 0x4a, 0x59, 0x09, 0x85, 0x35, 0x1a,
	0xea, 0x60, 0x5f, 0x5c, 0x7e, 0x0f, 0x00, 0x56, 0x8e, 0x3b, 0xde, 0x02, 0xfc, 0xa2, 0xc3, 0x53,
	0xf5, 0x2d, 0x7f, 0xe8, 0xc7, 0x67, 0xbb, 0xb2, 0xb9, 0x84, 0xec, 0xe1, 0x0d, 0x1c, 0x74, 0xc4,
	0x10, 0x95, 0xa9, 0x0f, 0x38, 0x3e, 0xe9, 0x69, 0x2e, 0x95, 0xc2, 0x48, 0x23, 0xc1, 0xa9, 0xbd,
	0xdd, 0x12, 0x8c, 0x67, 0x5b, 0x8a, 0xf5, 0x17, 0xfb, 0xfa, 0xef, 0xb8, 0xfe, 0x09, 0x00, 0x00,
	0xff, 0xff, 0xa3, 0xb3, 0xdb, 0x19, 0x31, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DictionaryClient is the client API for Dictionary service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DictionaryClient interface {
	AddNewWord(ctx context.Context, in *AddNewWordRequest, opts ...grpc.CallOption) (*AddNewWordResponce, error)
	GetByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*GetByIDResponce, error)
	Words(ctx context.Context, in *WordsRequest, opts ...grpc.CallOption) (*WordsResponce, error)
}

type dictionaryClient struct {
	cc *grpc.ClientConn
}

func NewDictionaryClient(cc *grpc.ClientConn) DictionaryClient {
	return &dictionaryClient{cc}
}

func (c *dictionaryClient) AddNewWord(ctx context.Context, in *AddNewWordRequest, opts ...grpc.CallOption) (*AddNewWordResponce, error) {
	out := new(AddNewWordResponce)
	err := c.cc.Invoke(ctx, "/pb.Dictionary/AddNewWord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryClient) GetByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*GetByIDResponce, error) {
	out := new(GetByIDResponce)
	err := c.cc.Invoke(ctx, "/pb.Dictionary/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryClient) Words(ctx context.Context, in *WordsRequest, opts ...grpc.CallOption) (*WordsResponce, error) {
	out := new(WordsResponce)
	err := c.cc.Invoke(ctx, "/pb.Dictionary/Words", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DictionaryServer is the server API for Dictionary service.
type DictionaryServer interface {
	AddNewWord(context.Context, *AddNewWordRequest) (*AddNewWordResponce, error)
	GetByID(context.Context, *GetByIDRequest) (*GetByIDResponce, error)
	Words(context.Context, *WordsRequest) (*WordsResponce, error)
}

func RegisterDictionaryServer(s *grpc.Server, srv DictionaryServer) {
	s.RegisterService(&_Dictionary_serviceDesc, srv)
}

func _Dictionary_AddNewWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNewWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServer).AddNewWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Dictionary/AddNewWord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServer).AddNewWord(ctx, req.(*AddNewWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dictionary_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Dictionary/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServer).GetByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dictionary_Words_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServer).Words(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Dictionary/Words",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServer).Words(ctx, req.(*WordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dictionary_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Dictionary",
	HandlerType: (*DictionaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNewWord",
			Handler:    _Dictionary_AddNewWord_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _Dictionary_GetByID_Handler,
		},
		{
			MethodName: "Words",
			Handler:    _Dictionary_Words_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dictionary.proto",
}
